"""add public flag to projects

Revision ID: d625d4d78acf
Revises: 0001
Create Date: 2026-04-07 11:30:49.711095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d625d4d78acf"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("public", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_constraint(op.f("users_github_id_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=False)
    op.create_unique_constraint(
        op.f("users_github_id_key"),
        "users",
        ["github_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("projects", "public")
    # ### end Alembic commands ###
